### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by JackMD** [JackMD/MysteryCrate#34]
### ToDo
Mention the stuff you would like to be added to this plugin and I will try my best to make it happen.
<br />
- [x] Floating text above the crates,
- [x] Particles on/off switch via `config.yml`,
- [x] Particles above the crate,
- [x] Add option for setting the `tick-delay`in `config.yml` to increase or decrease the timer. (Requested by @Haxley)
- [x] Add lore to the reward mentioned in `crates.yml`. (Requested by @Adam1609)
- [ ] Add multiple commands. (Requested by @95CivicSi)

**Comment by Haxley** [comment]
It would be nice if there was an option in the config to use the same key for all crates and let crates accept an amount of keys. For example, rather than requiring a "common" key to open a common crate and a "legendary" key to open a legendary crate, what if all crates could accept the same key but you can increase or decrease the amount of keys required to open each crate. 

I'm planning on implementing this plugin for my vote rewards. As it sits, players will probably be rewarded a common, rare, and legendary key. But I'd rather the vote reward be multiple of the same key and then the player can decide if they want to spend them on a bunch of common crates or throw them all into a single legendary crate.

**Comment by JackMD** [comment]
The slot machine timer seems to be interesting. And I am really not liking the single key configuration.

**Comment by Adam1609** [comment]
Great plugin
.
Can you add lore to the item please?

**Comment by JackMD** [comment]
@Adam1609. I didn't get that quite right. Adding lore to the crate key (which is already implemented) or adding lore to the reward?

**Comment by JackMD** [comment]
There it is @Adam1609. You can now add lore(s) to rewards.

**Comment by JackMD** [comment]
There it is @Haxley. The feature you requested has been added.

**Comment by JackMD** [comment]
Particles along with Floating Text have been added.

**Comment by GageGamesHD** [comment]
Maybe replace the vines in the crate opening with different colors of stained glass panes?

**Comment by JackMD** [comment]
@Haxley if you use Classic UI instead of Pocket UI then chest will match up on every device. Further reducing the slots 4 or 6 will cause trouble in determining whch slot will be in center. This plugin is made to match PC plugin. So that would be a not be likely to happen.

**Comment by JackMD** [comment]
@GageGamesHD I remember me trying to use panes or glass block instead of vines during the initial making of the plugin. I didn't like the way how glass panes are now place in chest. They get tilted sideways.

**Comment by MSG100TC** [comment]
## **Items showing Frequency**
Add an option to set the frequency of a certain item when showing up in the slots. A feature for more valuable items.

**Comment by JackMD** [comment]
Interesting. I think what you are trying to say is adding a `chance` to items.

**Comment by GageGamesHD** [comment]
Could you try to make particles circle the crates instead of water and smoke? Like this 
 
![866971026725eaca1b9657d060cd94f39e7b02e7](https://user-images.githubusercontent.com/34907865/40583596-3305718c-6160-11e8-96ac-f337335d1731.png)

and also when a player gets something that you set as rare in the config file, it announces it so the whole server can see. And maybe firework particle when you win an item?

**Comment by JackMD** [comment]
I will try

**Comment by GageGamesHD** [comment]
Alright, thanks.

**Comment by GageGamesHD** [comment]
Well don't do the firework particle after winning an item but make it do something.

**Comment by GageGamesHD** [comment]
It's fine if you can't do it.

**Comment by JackMD** [comment]
I will try to do it. But later and not now. I am working another private project. Need to complete that first and then will work on this.

**Comment by 95CivicSi** [comment]
It would be helpful to run multiple commands for a single item by either adding additional command lines or by putting the commands in an array.  Example:

```vote:
    drops:
      - name: "Money Drop"
        id: 339
        meta: 50
        amount: 1
        command: ["givemoney \"%PLAYER%\" 100000", "say %PLAYER% just won 100,000 from a vote key!" ]
    block: "41:0"```

**Comment by JackMD** [comment]
Added to `todo's`

**Comment by JackMD** [comment]
Didn't meant to close..

**Comment by JackMD** [comment]
@95CivicSi multiple commands are added

**Comment by JackMD** [comment]
Also @GageGamesHD the particles you requested have been added. There are now 5 particles for you to choose from. Set the required on in config.yml

**Comment by JackMD** [comment]
Closing this issue tab and making a new one. This is way too lengthy now.

**Comment by JackMD** [comment]
Mention the sstuff you want to be added in #67 from now on
